title: Jekyll Gemcode
email: jekyllgemcode@jekyll.com
description: >- # this means to ignore newlines until "baseurl:"
  Crie sites estáticos de forma sensacional com Jenkyll {Ruby}
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reinaldonunes.github.io/jenkyllSite/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  reinaldonunes

# Build settings
theme: minima
plugins:
  - jekyll-feed


